# Generated by Django 5.1.5 on 2026-03-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('socialscience', models.IntegerField()),
                ('marathi', models.IntegerField()),
                ('total', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('grade', models.CharField(default='NA', max_length=10)),
            ],
        ),
    ]
